grupo5J/appsecundaria/urls.py
from django.urls import path
from appsecundaria import views

urlpatterns = [
    path("",views.Index_vista,name="Index_vista"),
    path('alumno/<int:id>', views.Alumno_vista),
]

grupo5J/p_backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("appsecundaria.urls"))
]

grupo5J/appsecundaria/models.py
from django.db import models

# Create your models here.
class AlumnoT(models.Model):
    APaterno=models.CharField(max_length=50,verbose_name="Apellido paterno")
    AMaterno=models.CharField(max_length=50,verbose_name="Apellido materno")
    Nombre=models.CharField(max_length=50,verbose_name="Nombre(s)")
    Fecha_nacimiento=models.DateField(verbose_name='Fecha Nacimiento', null=False, blank=False)
    Fecha_ingreso=models.DateField(verbose_name='Fecha Ingreso',null=False,blank=False)

    class Meta:
        db_table="Alumnos"
        verbose_name="Alumno"
        verbose_name_plural="Alumnos"
    def __str__(self) -> str:
        return self.Nombre


class Frase(models.Model):
    comentario=models.TextField(verbose_name='Comentario',max_length=400)
    Alumno_fk=models.ForeignKey(AlumnoT,on_delete=models.CASCADE)

    class Meta:
        verbose_name="Frase"
        verbose_name_plural="frases"
    def __str__(self) -> str:
        return self.comentario

grupo5J/appsecundaria/views.py
from django.shortcuts import render, get_object_or_404
from.models import AlumnoT,Frase

# Create your views here.
def Index_vista(request):
    misalumnos=AlumnoT.objects.all().order_by("id") #nuevo más el diccionario
    return render(request,"index.html",{"misalumnos":misalumnos})

def Alumno_vista(request, id):
    alumno = get_object_or_404(AlumnoT,id=id)
    return render(request, 'alumno.html',{'misalumnos':alumno})

grupo5J/appsecundaria/templates/alumno.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
        <title>La frase</title>
    </head>
    <body>
    <h1>{{misalumnos.Nombre}}</h1>
    <ul>
        {% for i in misalumnos.frase_set.all %}

        <li>{{i.comentario}}</li>

        {% endfor %}
    </ul>
    </body>
</html>

grupo5J/appsecundaria/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'estilos.css' %}">
    <title>López jaja</title>
</head>
<body>
    <h1>hola mundo cruel</h1>
    <h1>Daniela López</h1>
    <hr> 
        {% for i in misalumnos %}
        <li> <a href="alumno/{{i.id}}">{{i.Nombre}}</a></li>
        {% endfor %}
    </hr>
    <script src="{% static 'script.js' %}"></script>
</body>
</html>